[colors.primary]
background = "#0f0f0f"
foreground = "#eadccc"

[colors.cursor]
text = "#0f0f0f"
cursor = "#eadccc"

[colors.vi_mode_cursor]
text = "#0f0f0f"
cursor = "#eadccc"

[colors.search.matches]
foreground = "#0f0f0f"
background = "#eadccc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#706a6a"
background = "#eadccc"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f0f0f"
red = "#e25d6c"
green = "#cea37f"
yellow = "#f4bb54"
blue = "#e2be8a"
magenta = "#ede4c8"
cyan = "#e8ab3b"
white = "#e6caab"

[colors.bright]
black = "#706a6a"
red = "#e9838f"
green = "#cea37f"
yellow = "#edb95a"
blue = "#eacea7"
magenta = "#ede4c8"
cyan = "#ecb95c"
white = "#eadccc"

[colors.dim]
black = "#eadccc"
red = "#e9838f"
green = "#cea37f"
yellow = "#edb95a"
blue = "#eacea7"
magenta = "#ede4c8"
cyan = "#ecb95c"
white = "#706a6a"
