accent = "#e2be8a"
cursor = "#eadccc"
foreground = "#eadccc"
background = "#0f0f0f"
selection_foreground = "#eadccc"
selection_background = "#e2be8a"

color0 = "#0f0f0f"
color1 = "#e25d6c"
color2 = "#cea37f"
color3 = "#f4bb54"
color4 = "#e2be8a"
color5 = "#ede4c8"
color6 = "#e8ab3b"
color7 = "#e6caab"
color8 = "#706a6a"
color9 = "#e9838f"
color10 = "#cea37f"
color11 = "#edb95a"
color12 = "#eacea7"
color13 = "#ede4c8"
color14 = "#ecb95c"
color15 = "#eadccc"
