$color = rgba(245, 245, 245, 1)
$inner_color = rgba(245, 245, 245, 0.66)
$outer_color = rgba(175, 82, 222, 1)
$font_color = rgba(28, 28, 28, 1)
$placeholder_color = rgba(28, 28, 28, 0.7)
$check_color = rgba(90, 200, 250, 1)
