# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.


general {
    col.active_border = rgba(f5f5f5ee) rgba(8e8e93ee) 45deg
}

decoration {
    rounding = 12

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        ignore_opacity = true
    }

    active_opacity = 0.85
    inactive_opacity = 0.75
}
