background            #f5f5f5
foreground            #1c1c1c

# black
color0  #f5f5f5
color8  #8e8e93

# red
color1  #ff3b30
color9  #ff6961

# green
color2  #34c759
color10 #34c759

# yellow
color3  #ffcc00
color11 #ffd60a

# blue
color4  #007aff
color12 #0a84ff

# magenta
color5  #af52de
color13 #af52de

#cyan
color6  #5ac8fa
color14 #64d2ff

#white
color7  #ffffff
color15 #1c1c1c


background_opacity 0.85
background_blur 8
window_margin_width 8
window_padding_width 8
