background            #f5f5f5
foreground            #000000

# black
color0  #f5f5f5
color8  #6b6b70

# red
color1  #ff3b30
color9  #d94a42

# green
color2  #34c759
color10 #34c759

# yellow
color3  #d4a800
color11 #cc9900

# blue
color4  #007aff
color12 #0a84ff

# magenta
color5  #af52de
color13 #af52de

#cyan
color6  #0095c8
color14 #00a6e0

#white
color7  #f0f0f0
color15 #000000


background_opacity 0.85
background_blur 8
window_margin_width 8
window_padding_width 8